/**
 * ScriptsPage
 * Page for managing video/post scripts generated by Marnee
 */

import React from "react";
import PageTransition from "../../Component/PageTransition";
import ScriptsSection from "./Scripts/ScriptsSection";

export default function ScriptsPage() {
  return (
    <PageTransition className="flex min-h-screen bg-[#f6f6f6]">
      <div className="flex-1 p-8">
        <ScriptsSection />
      </div>
    </PageTransition>
  );
}
